FROM       alpine
MAINTAINER missbsd@gmail.com

RUN  mkdir -p /usr/local/main
COPY ./bin/main.linux /usr/local/main/main
COPY ./.env.yml /usr/local/main/.env.yml
ADD ./dist /usr/local/main/web
RUN  mkdir -p /usr/local/main/webdata

WORKDIR /usr/local/main
CMD    ./main --mode production
