version: "3"

services:
  backend:
    container_name: zkeep_backend
    restart: always
    image: netb.co.kr:5000/zkeep
    ports:
      - "9303:9303"    
    volumes:
      - /home/zkeep/back/webdata:/usr/local/main/webdata
